# run: conda env create --file environment.yml
name: bmex-masses
dependencies:
- python=3.12
- anaconda
- pip
- numpy
- gunicorn
- pandas
- scipy
- pip:
  - tables
  - plotly>=5.13.0
  - dash==2.18.2
  - colorlover>=0.2.1
  - dash-bootstrap-components==1.6.0
  - kaleido
  - dash_breakpoints
